### ISSUE TITLE
Add support to Dark Theme

### ISSUE THREAD

**Issue by aimproxy** [dahenson/agenda#97]
Agenda doesn't have a dark theme, but I use dark theme in global mode and she works very well on Agenda, so I decide to fork this, create a branch a starting add a mode switch btn to change between dark and light themes!
![Screenshot from 2019-06-24 10 32 09](https://user-images.githubusercontent.com/47716563/60008137-67e15b00-966b-11e9-93ad-6ad0c30199e5.png)
![Screenshot from 2019-06-24 10 32 17](https://user-images.githubusercontent.com/47716563/60008140-69128800-966b-11e9-8e16-620391b26d6b.png)

I gonna make a pull request, but I have a little question, I have fork from `develop` branch but it's seems you are more development on `undo-feature`, so should I implement this functionality under `develop` or `undo-feature`?, any away I gonna make a pull request under develop branch!

**Comment by dahenson** [comment]
I am doing most of my work on the `undo-feature` branch right now, but you should be able to submit a pull request against the `develop` branch without a problem.

As far as the dark theme goes, I am planning on eventually supporting whatever global dark theme elementary decides to implement, but I do not plan on adding a per-app toggle switch as a stop-gap. While I appreciate your work, I will not be merging your toggle switch because I prefer the interface to stay focused task-oriented features and not cosmetic features.

If you have any stylesheet-specific pull requests in preparation for a global dark theme, I would appreciate it.
